### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by Lena-ActiveBridge** [activebridge/CabLook-backend#31]
![mobile_signup](https://user-images.githubusercontent.com/32668595/31553469-44e41bfc-b043-11e7-95ee-24afdff74215.jpg)
[houses png-s.zip](https://github.com/activebridge/CabLook-backend/files/1383062/houses.png-s.zip)
[png icons.zip](https://github.com/activebridge/CabLook-backend/files/1383063/png.icons.zip)

**Comment by galulex** [comment]
@Lena-ActiveBridge this is for [that repo](https://github.com/activebridge/EcoCab)
